### ISSUE TITLE
double free corruption on sintel example video

### ISSUE THREAD

**Issue by AlainBarthelemy** [Hemisphere-Project/HPlayer#19]

**Comment by Maigre** [comment]
it works for me...
try rpi-update / apt-get update / apt-get upgrade / apt-get dist-upgrade ...

**Comment by AlainBarthelemy** [comment]
indeed it is a .mkv

**Comment by Maigre** [comment]
For now, only mp4 / mov / avi files are authorized (i had to filter the file extension to dispatch between image / sound /video)
