### ISSUE TITLE
Bug to compile the player

### ISSUE THREAD

**Issue by SANCHca** [Hemisphere-Project/HPlayer#33]
Hi, 
I need this apps and so I try to install on my rasberry pi3, I install openFrameworks v0.9.3
but not to compil the player, 
That is my error: 

obj/linuxarmv6l/Release/src/omPlayer.o: fichier non reconnu: Fichier tronqué
collect2: error: ld returned 1 exit status
../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:382: recipe for target 'bin/HPlayer' failed
make[1]: *** [bin/HPlayer] Error 1
make[1]: Leaving directory '/home/pi/openFrameworks/apps/myApps/HPlayer'
../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:125: recipe for target 'Release' failed
make: *** [Release] Error 2

And I don't know what to do? If you can help me.

**Comment by Maigre** [comment]
Hi,
could you try to "make clean" and retry the compilation ?
i did not test HPlayer with OF 0.9.3, i will give it a try soon.
The error message you sent is only the failed result but i need the actual
error which should be displayed
earlier in the build log.
Could you send the complete log of the build ?

Best,
Thomas

2016-05-28 16:35 GMT+02:00 SANCHca <notifications@github.com>:

> Hi,
> I need this apps and so I try to install on my rasberry pi3, I install
> openFrameworks v0.9.3
> but not to compil the player,
> That is my error:
>
> obj/linuxarmv6l/Release/src/omPlayer.o: fichier non reconnu: Fichier
> tronqué
> collect2: error: ld returned 1 exit status
> ../../../libs/openFrameworksCompiled/project/makefileCommon/
> compile.project.mk:382: recipe for target 'bin/HPlayer' failed
> make[1]: *** [bin/HPlayer] Error 1
> make[1]: Leaving directory '/home/pi/openFrameworks/apps/myApps/HPlayer'
> ../../../libs/openFrameworksCompiled/project/makefileCommon/
> compile.project.mk:125: recipe for target 'Release' failed
> make: *** [Release] Error 2
>
> And I don't know what to do? If you can help me.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Hemisphere-Project/HPlayer/issues/33>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAq2wbZynUd_yUyFQt9O6w4IYDT03rQJks5qGFKzgaJpZM4IpFn3>
> .
>



-- 
<http://www.hemisphere-project.com/>

**Comment by SANCHca** [comment]
Hi, thank for your answer, that is complet error message: 

pi@raspberrypi:~/openFrameworks/apps/myApps/HPlayer $ make
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gtk+-3.0 
Compiling OF library for Release
make[1]: Entering directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gtk+-3.0 
/home/pi/openFrameworks/libs/openFrameworksCompiled/lib/linuxarmv6l/obj/Release/libs/openFrameworks/graphics/ofPolyline.d:1: warning: NUL character seen; rest of line ignored
/home/pi/openFrameworks/libs/openFrameworksCompiled/lib/linuxarmv6l/obj/Release/libs/openFrameworks/graphics/ofPolyline.d:8: warning: NUL character seen; rest of line ignored
/home/pi/openFrameworks/libs/openFrameworksCompiled/lib/linuxarmv6l/obj/Release/libs/openFrameworks/graphics/ofPolyline.d:9: warning: NUL character seen; rest of line ignored
/home/pi/openFrameworks/libs/openFrameworksCompiled/lib/linuxarmv6l/obj/Release/libs/openFrameworks/graphics/ofPolyline.d:10: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.
make[1]: Leaving directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project'
../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:125: recipe for target 'Release' failed
make: *** [Release] Error 

Thanks for your attention!

**Comment by Maigre** [comment]
Hi,
did you succeed with your compilation ?
A new "install from source" script is available, may be it could help ?
Best,
